---
image: dablang/dablangenv:0.4
before_script:
- gem install bundler
- bundle install --path=/cache/bundler
stages:
- prebuild
- build
- test
".build_base":
  stage: build
  tags: &1
  - ruby
  script: &2
  - bundle exec rake bin/cvm
  artifacts: &3
    paths:
    - bin/*
    - build/*
    - tmp/c_files.txt
    expire_in: 1 week
".test_base":
  stage: test
  tags: &5
  - ruby
  script: &6
  - bundle exec rake spec
FormatSpec:
  stage: prebuild
  tags:
  - ruby
  script:
  - bundle exec rake format_spec
RSpec:
  stage: prebuild
  tags:
  - ruby
  script:
  - bundle exec rspec
Rubocop:
  stage: prebuild
  tags:
  - ruby
  script:
  - bundle exec rubocop
ClangFormat:
  stage: prebuild
  tags:
  - ruby
  script:
  - bundle exec rake format:cpp_check
SortCheck:
  stage: prebuild
  tags:
  - ruby
  script:
  - bundle exec rake format:sort_check
".env_g_4_7":
  variables: &4
    CXX: g++-4.7
".env_clang_3_5":
  variables: &7
    CXX: clang++-3.5
Build g++-4.7:
  stage: build
  tags: *1
  script: *2
  artifacts: *3
  variables: *4
Test g++-4.7:
  stage: test
  tags: *5
  script: *6
  variables: *4
  dependencies:
  - Build g++-4.7
Build clang++-3.5:
  stage: build
  tags: *1
  script: *2
  artifacts: *3
  variables: *7
Test clang++-3.5:
  stage: test
  tags: *5
  script: *6
  variables: *7
  dependencies:
  - Build clang++-3.5
