image: dablang/dablangenv:0.1

before_script:
  - gem install bundler
  - bundle install --path=/cache/bundler

stages:
  - prebuild
  - build
  - test

.build_base: &build_base
  stage: build
  tags:
    - ruby
  script:
    - bundle exec rake bin/cvm

.test_base: &test_base
  stage: test
  tags:
    - ruby
  script:
    - bundle exec rake spec

RSpec:
  stage: prebuild
  tags:
    - ruby
  script:
    - bundle exec rspec

Rubocop:
  stage: prebuild
  tags:
    - ruby
  script:
    - bundle exec rubocop

.env_g_4_7: &env_g_4_7
  variables:
    COMPILER: g++-4.7

.env_g_4_8: &env_g_4_8
  variables:
    COMPILER: g++-4.8

.env_g_4_9: &env_g_4_9
  variables:
    COMPILER: g++-4.9

.env_g_5: &env_g_5
  variables:
    COMPILER: g++-5

.env_g_6: &env_g_6
  variables:
    COMPILER: g++-6

.env_clang_3_5: &env_clang_3_5
  variables:
    COMPILER: clang++-3.5

.env_clang_3_6: &env_clang_3_6
  variables:
    COMPILER: clang++-3.6

.env_clang_3_7: &env_clang_3_7
  variables:
    COMPILER: clang++-3.7

.env_clang_3_8: &env_clang_3_8
  variables:
    COMPILER: clang++-3.8

.env_clang_3_9: &env_clang_3_9
  variables:
    COMPILER: clang++-3.9

'Build g++-4.7':
  <<: *build_base
  <<: *env_g_4_7

'Test g++-4.7':
  <<: *test_base
  <<: *env_g_4_7

'Build g++-4.8':
  <<: *build_base
  <<: *env_g_4_8

'Test g++-4.8':
  <<: *test_base
  <<: *env_g_4_8

'Build g++-4.9':
  <<: *build_base
  <<: *env_g_4_9

'Test g++-4.9':
  <<: *test_base
  <<: *env_g_4_9

'Build g++-5':
  <<: *build_base
  <<: *env_g_5

'Test g++-5':
  <<: *test_base
  <<: *env_g_5

'Build g++-6':
  <<: *build_base
  <<: *env_g_6

'Test g++-6':
  <<: *test_base
  <<: *env_g_6

'Build clang++-3.5':
  <<: *build_base
  <<: *env_clang_3_5

'Test clang++-3.5':
  <<: *test_base
  <<: *env_clang_3_5

'Build clang++-3.6':
  <<: *build_base
  <<: *env_clang_3_6

'Test clang++-3.6':
  <<: *test_base
  <<: *env_clang_3_6

'Build clang++-3.7':
  <<: *build_base
  <<: *env_clang_3_7

'Test clang++-3.7':
  <<: *test_base
  <<: *env_clang_3_7

'Build clang++-3.8':
  <<: *build_base
  <<: *env_clang_3_8

'Test clang++-3.8':
  <<: *test_base
  <<: *env_clang_3_8

'Build clang++-3.9':
  <<: *build_base
  <<: *env_clang_3_9

'Test clang++-3.9':
  <<: *test_base
  <<: *env_clang_3_9

