image: dablang/dablangenv:0.5

before_script:
  - gem install bundler
  - bundle install --path=/cache/bundler

stages:
  - prebuild
  - build
  - test

.build_base:
  stage: build
  tags:
    - ruby
  script:
    - bundle exec rake bin/cvm
    - bundle exec rake bin/cdisasm
    - bundle exec rake bin/cdumpcov
  artifacts:
    paths:
    - bin/*
    - build/*
    - tmp/c_files.txt
    expire_in: 1 week

.test_base: &test_base
  stage: test
  tags:
    - ruby

.test_base_spec:
  <<: *test_base
  script:
    - bundle exec rake spec

.test_base_vm_spec:
  <<: *test_base
  script:
    - bundle exec rake vm_spec

.test_base_disasm_spec:
  <<: *test_base
  script:
    - bundle exec rake disasm_spec

.test_base_asm_spec:
  <<: *test_base
  script:
    - bundle exec rake asm_spec

.test_base_format_spec:
  <<: *test_base
  script:
    - bundle exec rake format_spec

.test_base_dumpcov_spec:
  <<: *test_base
  script:
    - bundle exec rake dumpcov_spec

FormatSpec:
  stage: prebuild
  tags:
    - ruby
  script:
    - bundle exec rake format_spec  

RSpec:
  stage: prebuild
  tags:
    - ruby
  script:
    - bundle exec rspec

Rubocop:
  stage: prebuild
  tags:
    - ruby
  script:
    - bundle exec rubocop

ClangFormat:
  stage: prebuild
  tags:
    - ruby
  script:
    - bundle exec rake format:cpp_check

SortCheck:
  stage: prebuild
  tags:
    - ruby
  script:
    - bundle exec rake format:sort_check

